#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# [*] represents the item cannot be modified after startup

# The blockchain auth type, shoudle be consistent with auth type in each chain config (e.g., bc1.yml)
# The auth type can be permissionedWithCert, permissionedWithKey, public.
# By default it is permissionedWithCert.
# permissionedWithCert: permissioned blockchain, using x.509 certificate to identify members.
# permissionedWithKey: permissioned blockchain, using public key to identify members.
# public: public blockchain, using public key to identify members.
auth_type: "permissionedWithCert" # [*]

# Logger settings
log:
  # Logger configuration file path
  config_file: ../config/wx-org1/log.yml

# Chains the node currently knows
blockchain:
  # chain id and its genesis block file path
  - chainId: chain1
    genesis: ../config/wx-org1/chainconfig/bc1.yml
#  - chainId: chain2
#    genesis: ../config/wx-org1/chainconfig/bc2.yml
#  - chainId: chain3
#    genesis: ../config/wx-org1/chainconfig/bc3.yml
#  - chainId: chain4
#    genesis: ../config/wx-org1/chainconfig/bc4.yml

node:
  org_id:            wx-org1.chainmaker.org
  priv_key_file:     ../config/wx-org1/certs/node/consensus1/consensus1.sign.key
  cert_file:         ../config/wx-org1/certs/node/consensus1/consensus1.sign.crt
  cert_cache_size:   1000
  pkcs11:
    enabled: false
    library: /usr/local/lib64/pkcs11/libupkcs11.so      # path to the so file of pkcs11 interface
    label: HSM                                          # label for the slot to be used
    password: 11111111                                  # password to logon the HSM
    session_cache_size: 10                              # size of HSM session cache, default to 10
    hash: "SHA256"                                      # [*] SHA256/SM3 hash algorithm used to compute SKI

# Network Settings
net:
  # Network provider, can be libp2p or liquid.
  # libp2p: using libp2p components to build the p2p module.
  # liquid: a new p2p module we build from 0 to 1.
  # This item must be consistent across the blockchain network.
  provider: LibP2P

  # The address and port the node listens on.
  # By default, it uses 0.0.0.0 to listen on all network interfaces.
  listen_addr: /ip4/0.0.0.0/tcp/11301

  # Max stream of a connection.
  # peer_stream_pool_size: 100

  # Max number of peers the node can connect.
  # max_peer_count_allow: 20

  # The strategy for eliminating node when the count of connecting peers reach the max value.
  # It could be: 1 Random, 2 FIFO, 3 LIFO. The default strategy is LIFO.
  # peer_elimination_strategy: 3

  # The seeds peer list used to join in the network when starting.
  # The connection supervisor will try to dial seed peer whenever the connection is broken.
  # Example ip format: "/ip4/127.0.0.1/tcp/11301/p2p/"+nodeid
  # Example dns format："/dns/cm-node1.org/tcp/11301/p2p/"+nodeid
  seeds:
    - "/ip4/127.0.0.1/tcp/11301/p2p/QmcQHCuAXaFkbcsPUj7e37hXXfZ9DdN7bozseo5oX4qiC4"
    - "/ip4/127.0.0.1/tcp/11302/p2p/QmeyNRs2DwWjcHTpcVHoUSaDAAif4VQZ2wQDQAUNDP33gH"
    - "/ip4/127.0.0.1/tcp/11303/p2p/QmXf6mnQDBR9aHauRmViKzSuZgpumkn7x6rNxw1oqqRr45"
    - "/ip4/127.0.0.1/tcp/11304/p2p/QmRRWXJpAVdhFsFtd9ah5F4LDQWFFBDVKpECAF8hssqj6H"
    #    - "/ip4/127.0.0.1/tcp/11305/p2p/QmVSCXfPweL1GRSNt8gjcw1YQ2VcCirAtTdLKGkgGKsHqi"
    #    - "/ip4/127.0.0.1/tcp/11306/p2p/QmPpx5dTZ4A1GQ9a4nsSoMJ72AtT3VDgcX2EVKAFxJUHb1"
    #    - "/ip4/127.0.0.1/tcp/11307/p2p/QmVGSXfz6vgXBjWiZh5rV8T5nutevvunHAfEoe6Sh5Xcyx"

  # Network tls settings.
  tls:
    # Enable tls or not. Currently it can only be true...
    enabled: true

    # TLS private key file path.
    priv_key_file: ../config/wx-org1/certs/node/consensus1/consensus1.tls.key

    # TLS Certificate file path.
    cert_file:     ../config/wx-org1/certs/node/consensus1/consensus1.tls.crt

    # The blacklisted peers in p2p network.
    # blacklist:
    # The addresses in blacklist.
    # The address format can be ip or ip+port.
    # addresses:
    #   - "127.0.0.1:11301"
    #   - "192.168.1.8"

    # The node ids in blacklist.
    # node_ids:
  #   - "QmeyNRs2DwWjcHTpcVHoUSaDAAif4VQZ2wQDQAUNDP33gH"

# Transaction pool settings
# Other txpool settings can be found in tx_Pool_config.go
txpool:
  # txpool type, can be signle or batch.
  # By default the txpool type is single.
  pool_type: "single"

  # Max transaction count in txpool.
  # If txpool is full, the following transactions will be discarded.
  max_txpool_size: 50000

  # Max config transaction count in config txpool.
  max_config_txpool_size: 10

  # Interval of creating a transaction batch, only for batch txpool, in ms.
  # batch_create_timeout: 200


# RPC service setting
rpc:
  # RPC type, can only be grpc now
  provider: grpc  # [*]

  # RPC port
  port: 12301

  # Interval of checking trust root changes, in seconds.
  # If changed, the rpc server's root certificate pool will also change.
  # Only valid if tls is enabled.
  # The minium value is 10s.
  check_chain_conf_trust_roots_change_interval: 60

  # Rate limit related settings
  # Here we use token bucket to limit rate.
  ratelimit:
    # If rate limit is enabled.
    enabled: false

    # Rate limit type
    # 0: limit globally, 1: limit by ip
    type: 0

    # Token number added to bucket per second.
    # -1: unlimited, by default is 10000.
    token_per_second: -1

    # Token bucket size.
    # -1: unlimited, by default is 10000.
    token_bucket_size: -1

  # Rate limit settings for subscriber
  subscriber:
    ratelimit:
      token_per_second: 100
      token_bucket_size: 100

  # RPC TLS settings
  tls:
    # TLS mode, can be disable, oneway, twoway.
    mode:           twoway

    # RPC TLS private key file path
    priv_key_file:  ../config/wx-org1/certs/node/consensus1/consensus1.tls.key

    # RPC TLS public key file path
    cert_file:      ../config/wx-org1/certs/node/consensus1/consensus1.tls.crt

  # RPC blacklisted ip addresses
  blacklist:
    addresses:
    # - "127.0.0.1"

# Monitor related settings
monitor:
  # If monitor service is enabled or not
  enabled: false

  # Monitor service port
  port: 14321

# PProf Settings
pprof:
  # If pprof is enabled or not
  enabled: false

  # PProf port
  port: 24321

# Consensus related settings
consensus:
  raft:
    # We should take a snapshot after how many blocks.
    # If raft nodes change, a snapshot is taken immediately.
    snap_count: 10

    # Saving wal asynchronously or not.
    async_wal_save: true

    # Min time unit in rate election and heartbeat.
    ticker: 1

# Storage config settings
# Contains blockDb、stateDb、historyDb、resultDb、contractEventDb
#
# blockDb: block transaction data,                          support leveldb、mysql、badgerdb
# stateDb: world state data,                                support leveldb、mysql、badgerdb
# historyDb: world state change history of transactions,    support leveldb、mysql、badgerdb
# resultDb: transaction execution results data,             support leveldb、mysql、badgerdb
# contractEventDb: contract emit event data, support        support mysql
#
# provider、sqldb_type cannot be changed after startup
# store_path、dsn the content cannot be changed after startup
storage:
  # Default store path
  store_path: ../data/org1/ledgerData1 # [*]

  # Prefix for mysql db name
  # db_prefix: org1_

  # Minimum block height not allowed to be archived
  unarchive_block_height: 300000

  # Symmetric encryption algorithm for writing data to disk. can be sm4 or aes
  # encryptor: sm4    # [*]

  # Symmetric encryption key:16 bytes key
  # If pkcs11 is enabled, it is the keyID
  # encrypt_key: "1234567890123456"

  # Block db config
  blockdb_config:
    # Databases type support leveldb、sql、badgerdb
    provider: leveldb # [*]
    # Provider used leveldb must be set leveldb_config
    leveldb_config:
      # LevelDb store path
      store_path: ../data/org1/blocks
      write_buffer_size: 1024
      block_write_buffer_size: 1024

    # Example for sql provider
    # Databases type support leveldb、sql、badgerdb
    # provider: sql # [*]
    # Provider used sql must be set sqldb_config
    # sqldb_config:
    # Sql db type, can be mysql、sqlite. sqlite only for test
    # sqldb_type: mysql # # [*]
    # Mysql connection info, the database name is not required. such as:  root:admin@tcp(127.0.0.1:3306)/
    # dsn: root:password@tcp(127.0.0.1:3306)/

    # Example for badgerdb provider
    # Databases type support leveldb、sql、badgerdb
    # provider: badgerdb
    # Provider used badgerdb must be set badgerdb_config
    # badgerdb_config:
    # BadgerDb store path
    # store_path: ../data/wx-org1.chainmaker.org/history
    # Whether compression is enabled for stored data, default is 0: disabled
    # compression: 0
    # Key and value are stored separately when value is greater than this byte, default is 1024 * 10
    # value_threshold: 256
    # Number of key value pairs written in batch. default is 128
    # write_batch_size: 1024

  # State db config
  statedb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/state

  # History db config
  historydb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/history

  # Result db config
  resultdb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/result

  # Disable db config, If it is set to false, MySQL needs to be contract_eventdb_config
  disable_contract_eventdb: true
  # Contract event db config
  contract_eventdb_config:
    # Event db only support sql
    provider: sql
    # Sql db config
    sqldb_config:
      # Event db only support mysql
      sqldb_type: mysql
      # Mysql connection info, such as:  root:admin@tcp(127.0.0.1:3306)/
      dsn: root:password@tcp(127.0.0.1:3306)/

